### ISSUE TITLE
Feature Request: Custom job names

### ISSUE THREAD

**Issue by agraubert** [broadinstitute/canine#3]
Allow user to specify custom names for array jobs, instead of naming by index.

Firecloud adapter should default to provide entity names as custom job names, if not provided by user

**Comment by agraubert** [comment]
Okay, so it seems like overall, nobody really needs the `jobs/` directory to be labeled with entity names, so here's my compromise:

1. `jobs/` stays numbered by the array task id
2. Custom aliases are set within `setup.sh` like other canine variables
3. The `output/` folder will use custom aliases (which requires that the aliases all be unique)
4. The job alias will be included in the output dataframe from `Orchestrator.run_pipeline()` a la #5

**Comment by hurrialice** [comment]
That is beautiful! :clap:

**Comment by agraubert** [comment]
closed in 63cc655e2cf399704247cbbca46c5b6ea7636fb8
