### ISSUE TITLE
If default GCP project is not set, immediately raise error in the constructor

### ISSUE THREAD

**Issue by julianhess** [broadinstitute/canine#36]
Currently, Canine can progress quite far if a default project is not set up, and crash with a cryptic stack trace:

https://files.slack.com/files-pri/T1YPV3RLL-FUTTHHZ88/image.png

We should explicitly capture `self.config["project"] is None` and raise an informative exception.

**Comment by agraubert** [comment]
👍 This should be a pretty easy fix, but I do want to ensure that we don't raise any google-related errors until the user tries to do something google-related (ie: constructing a transient backend or attempting to localize a gs file). We need to be able to run in environments where gcloud is not configured (ie: run the dummy backend in the test environment)
