### ISSUE TITLE
Feature request: override input stringification

### ISSUE THREAD

**Issue by julianhess** [broadinstitute/canine#8]
Often times, we want inputs to correspond to arrays of command line arguments (not just single strings). For example, I might want to run

```foo --arg1 bar baz --arg2 doo```

with the following configuration dict:

```
inputs:
  arg1: bar baz
  arg2: doo
script:
  - foo --arg1 $arg1 --arg2 $arg2
```

However, this is incompatible with Canine, since any inputs that contain spaces will be wrapped in single quotes by the stringification here:

https://github.com/broadinstitute/canine/blob/bdd42083cef0def94a5c53fd3be9b859a1200a07/canine/orchestrator.py#L118

and thus Canine will dispatch my job like so
```
foo --arg1 'bar baz' --arg2 doo
```

which will break many tools out there that expect `--arg1` to be a space-delimited list of multiple arguments, e.g. anything using Python's `argparse` module:

`argparse.ArgumentPareser().add_argument("arg1", nargs = "+")`

This will also break things if inputs are being used to put together arbitrary chunks of command line. Qing ran into the following:

>I have `gatk: gatk --java-options -Xmx10g`, which Canine will translate into `export gatk="'gatk --java-options ....'"`. and it cannot find `'gatk`

I think this would be best controlled in the override section — if the localization type is `None`, then `prepare_job_inputs` should strip any stringification-added wrapping single quotes here:

https://github.com/broadinstitute/canine/blob/bdd42083cef0def94a5c53fd3be9b859a1200a07/canine/localization/base.py#L477-L480

This is consistent with how the "null" type localization is already described in the [Canine docs](https://github.com/broadinstitute/canine/blob/master/pipeline_options.md#overrides), i.e.

* `null`: Forces the input to be treated as a plain string. No handling whatsoever will be applied to the input.

What do you think?

**Comment by agraubert** [comment]
So right now, this actually occurs in localization, when the setup script is put together:
https://github.com/broadinstitute/canine/blob/master/canine/localization/base.py#L539

The stringify step is not responsible for quoting, it just makes sure that objects are strings, so in this case, no effect. I'm not opposed to changing the quoting so that the null override is not quoted, but default handling and other overrides still get quoted.  Does that sound okay?

**Comment by agraubert** [comment]
@julianhess Actually, I'm thinking that maybe these quotes are also redundant? Like, just use `shlex.quote` or nothing for the null override:

https://github.com/broadinstitute/canine/blob/bdd42083cef0def94a5c53fd3be9b859a1200a07/canine/localization/base.py#L537

**Comment by agraubert** [comment]
Fixed: now the double-quoting is fixed. The `null` override is not necessary
